import type { Metadata, Viewport } from "next";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { fontSans } from "@/lib/fonts";
import { SearchProvider } from "@/contexts/search-context";
import { cn } from "@/lib/utils";
import { AppProviders } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  colorScheme: "dark light",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fontSans.variable}`} suppressHydrationWarning>
      <body className={cn("font-sans [scrollbar-gutter:stable]")}>
        <div className="h-full">
          <NuqsAdapter>
            <TooltipProvider delayDuration={250}>
              <SearchProvider>
                <AppProviders>
                  {children}
                  {/* component search kayaknya buat sendiri aja, punya dia bnayk kli lib */}
                </AppProviders>
              </SearchProvider>
            </TooltipProvider>
          </NuqsAdapter>
        </div>
      </body>
    </html>
  );
}
