import type { Settings } from "meilisearch";

export const templateIndexSettings: Settings = {
  searchableAttributes: [
    "name",
    "searchKeywords",
    "searchSynonyms",
    "searchUseCases",
    "searchableText",
    "tagline",
    "searchSummary",
    "description",
    "stacks",
    "searchFeatures",
    "content",
    "allText",
  ],
  filterableAttributes: ["type", "templateType", "stackSlugs", "searchUseCases", "searchAudiences", "searchStyleTags", "searchLocales"],
  sortableAttributes: ["stars", "publishedAt", "updatedAt", "lastCommitDate", "popularityScore", "freshnessScore", "searchScore"],
  displayedAttributes: [
    "id",
    "name",
    "slug",
    "tagline",
    "description",
    "type",
    "templateType",
    "websiteUrl",
    "demoUrl",
    "repositoryUrl",
    "stars",
    "forks",
    "publishedAt",
    "updatedAt",
    "lastCommitDate",
    "stacks",
    "stackSlugs",
    "searchSummary",
    "searchKeywords",
    "searchUseCases",
    "searchAudiences",
    "searchFeatures",
    "searchStyleTags",
    "searchSynonyms",
    "searchLocales",
    "searchEmbeddingRef",
    "popularityScore",
    "freshnessScore",
    "searchScore",
    "searchManualBoost",
  ],
  rankingRules: [
    "words",
    "typo",
    "proximity",
    "attribute",
    "sort",
    "exactness",
    "searchScore:desc",
    "searchManualBoost:desc",
    "popularityScore:desc",
    "freshnessScore:desc",
    "stars:desc",
  ],
  stopWords: ["template", "templates", "website", "websites", "best", "for", "with"],
  synonyms: {
    ecommerce: ["e-commerce", "online store", "toko online", "shop", "store"],
    "e-commerce": ["ecommerce", "online store", "toko online"],
    saas: ["software", "app", "startup software"],
    portfolio: ["personal site", "showcase", "personal website"],
    dashboard: ["admin panel", "panel admin", "backoffice"],
    blog: ["article site", "content site", "writing site"],
    agency: ["studio", "service business", "company site"],
    restoran: ["restaurant", "food business", "cafe"],
    toko: ["store", "shop", "ecommerce"],
  },
  typoTolerance: {
    enabled: true,
    minWordSizeForTypos: {
      oneTypo: 4,
      twoTypos: 8,
    },
    disableOnWords: ["nextjs", "react", "vue", "nuxt", "astro", "sveltekit", "tailwind", "typescript"],
  },
};
